# Generated by Django 3.0.8 on 2020-08-26 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.IntegerField(primary_key=True, auto_created=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('hid', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('posted_on', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bday', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=True)),
                ('dated', models.DateTimeField(auto_now_add=True)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.NewsFeed', unique=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.NewsFeed', unique=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('hack_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.NewsFeed', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Profile')),
            ],
        ),
    ]
