# Generated by Django 3.0.8 on 2020-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
