# Generated by Django 3.0.8 on 2020-08-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200830_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='date',
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='posted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
