# Generated by Django 3.0.8 on 2020-09-01 19:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200831_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='hack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.NewsFeed'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userdeleted',
            name='hid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.NewsFeed'),
        ),
        migrations.AlterField(
            model_name='userread',
            name='hid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.NewsFeed'),
        ),
    ]
